# Setup

In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/book-reviews/goodreads_data_dictionary.csv
/kaggle/input/book-reviews/goodreads_reviews.csv
/kaggle/input/book-reviews/goodreads_works.csv

# Test Group 1
## String to int behavior

In [2]:
a=pd.DataFrame({'x':[39,90,127],'y':[60,777,90754]})

In [3]:
a.x.dtype

dtype('int64')

In [4]:
a.x.astype(str)

0     39
1     90
2    127
Name: x, dtype: object

In [5]:
a

     x      y
0   39     60
1   90    777
2  127  90754

In [6]:
a.y.astype(str)

0       60
1      777
2    90754
Name: y, dtype: object

In [7]:
a['z']=[9^9,1234567890123,89]

In [8]:
a

     x      y              z
0   39     60              0
1   90    777  1234567890123
2  127  90754             89

In [9]:
b=pd.DataFrame({'x':[39.9,90,127],'y':[60,777.7,90754]})

In [10]:
b.x.dtype

dtype('float64')

In [11]:
b

       x        y
0   39.9     60.0
1   90.0    777.7
2  127.0  90754.0

In [12]:

#b.x.astype(str)
#pd.options.display.float_format = '{:,.0f}'

# Test Group 2
# define a function to find a substring in a string

In [13]:
test_str="fiction, fantasy, young adult, romance"
genre1="fantasy"
genre2='thriller'
def find_genre(genre):
    if test_str.find(genre) > 0:
        print("it's here") #replace with return True
    else:
        print("not here") #replace with return False
find_genre(genre2)

not here

In [14]:
test_str="fiction, fantasy, young adult, romance"
genre1="fantasy"
genre2='thriller'
def search_genre(genre):
    if genre in test_str:
        print("it's here") #replace with return True
    else:
        print("not here") #replace with return False
search_genre(genre1)

it's here

# Test Group 3
## Split strings in column of dataframe into lists, filter a column with the items in the list

In [15]:
book_path="/kaggle/input/book-reviews/goodreads_works.csv"

books=pd.read_csv(book_path)

In [16]:
books['similar_books']=books.similar_books.fillna('0') #take care of those pesky NaNs before (but after) they make problems downstream

In [17]:
similar_split=books.similar_books.str.split(', ').apply(lambda x:[int(n) for n in x]) #make the strings into ints so that the type matches when we go to filter

In [18]:
JP=similar_split.loc[books.original_title == 'Jurassic Park'] #for testing purposes, I am pulling a row that I know is not null

In [19]:
JP.str.get(1) #testing that the data is correct because the searches weren't returning what was expected

3546    397139
Name: similar_books, dtype: int64

In [20]:
JP.iloc[0]

[1882596, 397139, 2318370, 2416056, 22533, 3419]

In [21]:
if any(books['work_id'].isin(JP)) == True: #this doesn't work...
    print(books.original_title)

In [22]:
#reviews.loc[reviews.country.isin(['Italy', 'France'])] example from the lesson to confirm correct syntax

books.loc[books.work_id.isin(JP.iloc[0])]

,work_id,isbn,isbn13,original_title,author,original_publication_year,num_pages,description,genres,image_url,reviews_count,text_reviews_count,5_star_ratings,4_star_ratings,3_star_ratings,2_star_ratings,1_star_ratings,ratings_count,avg_rating,similar_books
1403,3419,034541957X,9.780345e+12,Moreta: Dragonlady Of Pern,Anne McCaffrey,1983.0,286.0,An air of pleasant anticipation hung so thickl...,"fantasy, paranormal, fiction, young-adult, rom...",https://s.gr-assets.com/assets/nophoto/book/11...,31191,355,8031,8116,5951,1100,162,23360,4.0,1040567
3323,1882596,0553288202,9.780553e+12,The Fall of Hyperion,Dan Simmons,1990.0,517.0,In the stunning continuation of the epic adven...,"fiction, fantasy, paranormal, mystery, thrille...",https://images.gr-assets.com/books/1429215870m...,94720,2366,30957,25835,11110,2520,690,71112,4.2,"1270006, 1494156, 2020929, 1396625"
3440,397139,0553564927,9.780554e+12,Star Wars: The Last Command,Timothy Zahn,1993.0,467.0,The embattled Republic reels from the attacks ...,"fiction, fantasy, paranormal, young-adult",https://images.gr-assets.com/books/1451092026m...,49218,859,15658,13776,5871,893,168,36366,4.2,806845
3655,2318370,1400064562,9.781400e+12,Jaws,Peter Benchley,1974.0,320.0,"""Relentless terror."" The Philadelphia Inquirer...","fiction, mystery, thriller, crime",https://images.gr-assets.com/books/1327958767m...,137459,2358,39041,36724,25309,6046,1895,109015,4.0,"284389, 1945267"
3811,2416056,2266079999,9.782266e+12,Contact,Carl Sagan,1985.0,580.0,For centuries humanity has dreamed of life and...,"fiction, fantasy, paranormal, non-fiction",https://images.gr-assets.com/books/1408792653m...,164409,2197,38730,36729,18286,3437,899,98081,4.1,"75443, 1253407, 4273, 40712, 3333881"
4028,22533,0099446782,9.780099e+12,The Silence of the Lambs,Thomas Harris,1988.0,338.0,There's a killer on the loose who knows that b...,"fiction, mystery, thriller, crime",https://images.gr-assets.com/books/1390426249m...,508649,4009,167123,125362,55888,12930,10283,371586,4.1,"6294853, 859111, 2812184, 593515, 881425, 1945..."

Conclusion Steps to Take for Implementation
1. Replace original column in df with split column `similar_split=books.similar_books.str.split(', ').apply(lambda x:[int(n) for n in x])`
2. Use filtering/condition to pull a row...most likely a title... and assign to a variable `JP=similar_split.loc[books.original_title == 'Jurassic Park']`
3. Run the index selection `books.loc[books.work_id.isin(JP.iloc[0])]`

***Important Notes***
- step one will use the df['column']= for assignment
- step two will need a generic variable like 'row' and the == will be in a variable as well (like 'title')
- step three will have updated variable but iloc index will still be 0